import Head from 'next/head';
import styles from '../styles/Home.module.css';
import LoggedIn from '../components/loggedin/LoggedIn';
import Dashboard from '../components/dashboard/Dashboard';
import { useAuth } from '../providers/AuthUserContext';

export default function Home() {
  const { loading } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Scales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoggedIn>{!loading && <Dashboard />}</LoggedIn>
    </div>
  );
}
