import Head from 'next/head';
import styles from '../styles/Home.module.css';
import LoggedIn from '../components/loggedin/LoggedIn';
import Dashboard from '../components/dashboard/Dashboard';
import Loading from '../components/dashboard/Loading';
import { Modal } from '@mui/material';
import { useAuth } from '../providers/AuthUserContext';

export default function Home() {
  const { loading } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoggedIn>
        {loading && (
          <Modal open={loading} sx={{ width: '100vw', height: '100vh' }}>
            <Loading />
          </Modal>
        )}
        {!loading && <Dashboard />}
      </LoggedIn>
    </div>
  );
}
