import Head from 'next/head';
import { useState } from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Dashboard from '../components/dashboard/Dashboard';
import SignUp from '../components/signup/SignUp';
import SignIn from '../components/signin/SignIn';

export default function Home() {
  const [mainView, setMainView] = useState('signin');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {mainView === 'signin' && <SignIn mainView={mainView} setMainView={setMainView} />}
      {mainView === 'signup' && <SignUp mainView={mainView} setMainView={setMainView} />}
      {mainView === 'dashboard' && <Dashboard mainView={mainView} setMainView={setMainView} />}
    </div>
  );
}
