import SignUpView from '../components/signup/SignUpView';
import SignInView from '../components/signin/SignInView';
import { useState } from 'react';
import Head from 'next/head';

export default function SignIn() {
  const [signInView, setSignInView] = useState('signin');

  return (
    <div className={null}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {signInView === 'signin' && (
        <SignInView signInView={signInView} setSignInView={setSignInView} />
      )}
      {signInView === 'signup' && (
        <SignUpView signInView={signInView} setSignInView={setSignInView} />
      )}
    </div>
  );
}
